steps:
    # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/bulletin-board-284204/testcicd", "."]

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/bulletin-board-284204/testcicd"]



