steps:
    # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/velvety-maker-283305/testcicd", "."]

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/velvety-maker-283305/testcicd"]



